name: finanzapp
description: App de finanzas personales para gestionar tus ingresos y gastos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+4
  path: ^1.8.2
  provider: ^6.0.5
  flutter_riverpod: ^2.1.0
  fl_chart: ^0.64.0
  csv: ^5.0.1
  pdf: ^3.8.1
  printing: ^5.9.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_local_notifications: ^19.0.0
  intl: ^0.18.0
  excel: ^2.1.0
  flutter_timezone: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true